# pure pursuit parameters
lookahead_distance: 1.0
end_threshold: 0.25
speed: 4.0
kp: 0.175
ki: 0.0
kd: 0.030
# THIS WORKS!!!

# lane detector parameters
lookahead_distance_homog: 0.8

# homography parameters
left_lane_offset: 385
right_lane_offset: 485

# safety controller parameters
look_ahead_time: 0.5
half_car_width: 0.2
ignore_close_distance: 0.1
detections_required: 3

# topics
# drive_topic: /drive
drive_topic: /vesc/ackermann_cmd_mux/input/navigation
odom_topic: /odom
lane_topic: /lane
lookahead_topic: /lookaheadpoint
